/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.ItemEvent;

/**
 *
 * @author giovanni
 */
public class JP_Logout extends javax.swing.JPanel {

    /**
     * Creates new form JP_Logout
     */
    public JP_Logout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jl_nome = new javax.swing.JLabel();
        jl_cognome = new javax.swing.JLabel();
        jl_addetto = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jtf_cognome = new javax.swing.JTextField();
        jcb_addetto = new javax.swing.JComboBox();

        jButton1.setText("Logout");

        jl_nome.setText("Nome");

        jl_cognome.setText("Cognome");

        jl_addetto.setText("Addetto");

        jtf_nome.setText("Nome");

        jtf_cognome.setText("Cognome");

        jcb_addetto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modelleria", "Produzione"}));
        jcb_addetto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_addettoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_cognome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_addetto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_addetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jl_nome)
                    .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cognome)
                    .addComponent(jtf_cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_addetto)
                    .addComponent(jcb_addetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_addettoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_addettoItemStateChanged
        // TODO add your handling code here:
               
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //System.out.println(ItemEvent.SELECTED);
            System.out.println(jcb_addetto.getSelectedItem());
        }
    }//GEN-LAST:event_jcb_addettoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jcb_addetto;
    private javax.swing.JLabel jl_addetto;
    private javax.swing.JLabel jl_cognome;
    private javax.swing.JLabel jl_nome;
    private javax.swing.JTextField jtf_cognome;
    private javax.swing.JTextField jtf_nome;
    // End of variables declaration//GEN-END:variables
}
