/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import client.rest.UtenteClient;
import com.google.gson.*;
import org.codehaus.jettison.json.*;

/**
 *
 * @author giovanni
 */
public class JP_Login extends javax.swing.JPanel {

    /**
     * Creates new form JP_Login
     */
    public JP_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_username = new javax.swing.JLabel();
        jtf_username = new javax.swing.JTextField();
        jl_password = new javax.swing.JLabel();
        jtf_password = new javax.swing.JTextField();
        jb_login = new javax.swing.JButton();

        jl_username.setText("Username");

        jl_password.setText("Password");

        jb_login.setText("Login");
        jb_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_username)
                    .addComponent(jtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_password)
                    .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_login))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public class Utente {
         public String id_utente;
         public String nome;
         public String cognome;
         public String azienda;
         public String cf_piva;
         public String via;
         public String citta;
         public String email;
         public String fax;
         public String telefono;
         public String cellulare;
         public String note;
         public String livello_utente;
         public String password;
         public String username;
    }
    
    private void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_loginActionPerformed
        // TODO add your handling code here:
        UtenteClient client = new UtenteClient();
        String risposta = client.findAll_JSON(String.class);
        //System.out.println(risposta_mirata);
        Gson gson = new GsonBuilder().create();
        JSONObject jso;
        try {
            jso = new JSONObject(risposta);
            JSONArray ja = jso.getJSONArray("utente");
            for (int i = 0; i < ja.length(); i++) {
               JSONObject jsonSection = ja.getJSONObject(i);
               Utente utente_ins = gson.fromJson(jsonSection.toString(), Utente.class);
               if (utente_ins.username.equals(user_text.getText())) {
                    if (utente_ins.password.equals(pass_text.getText()))
                        loggato.setText("sei loggato");
                    else
                        loggato.setText("non sei loggato");
               }
               //lista.add(utente_ins);
            }
            //System.out.println(utente_ins.username);
        }
        catch (JSONException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        client.close();
        //Utente prova;
        //prova = (Utente) lista.get(0);
        System.out.println(
                "username: " + jtf_username.getText() + "\t" +
                "password: " + jtf_password.getText() 
                );
    }//GEN-LAST:event_jb_loginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_login;
    private javax.swing.JLabel jl_password;
    private javax.swing.JLabel jl_username;
    private javax.swing.JTextField jtf_password;
    private javax.swing.JTextField jtf_username;
    // End of variables declaration//GEN-END:variables
}
